### ISSUE TITLE
A fresh install of gatsby-source-wagtail complains about graphql-request dependency

### ISSUE THREAD

**Issue by fabienheureux** [NathHorrigan/gatsby-source-wagtail#30]
Will fix in an upcoming PR, just wanted to keep track 😁

**Comment by fabienheureux** [comment]
Closed by https://github.com/GrappleGQL/gatsby-source-wagtail/pull/29/files

**Comment by IAmNatch** [comment]
I think we may need to release this on NPM. Was still encountering this error on fresh install, had to directly point yarn at the repo with "GrappleGQL/gatsby-source-wagtail"

**Comment by lazarkostic** [comment]
It looks like the issue is still present after installing NPM package. 
Can you please make sure to deploy/release the fix? 
Thanks 🙂
